// NOTE: These translations are machine-generated and may not be accurate.
// They should be reviewed by a professional translator.

const translations = {
  en: {
    gameTitle: "Beads Shooter",
    score: "Score",
    highScore: "High Score",
    level: "Level",
    confirm: "Confirm",
    close: "Close",
    reset: "Reset",
    save: "Save",
    ad: "AD",
    cancel: "Cancel",
    menu: "MENU",
    chances: "CHANCES",
    help: "Help",
    helpLine1: "Aim with the mouse and click to shoot.",
    helpLine2: "Match 3 or more bubbles of the same color to pop them.",
    helpLine3: "Clear all bubbles to advance to the next level.",
    itemAim: "AIM",
    itemBomb: "BOMB",
    itemAimActive: "AIM\nACTIVE",
    itemAimTitle: "Aim Guide",
    itemAimDescription:
      "Shows the exact path of the bubble for a short time. Watch an ad to get this item?",
    itemBombTitle: "Bomb Bubble",
    itemBombDescription:
      "Changes the current bubble into a powerful bomb. The bomb will destroy nearby bubbles. Watch an ad to get this item?",
    settings: "Settings",
    sound: "Sound",
    masterVolume: "Master Volume",
    sfxVolume: "SFX Volume",
    musicVolume: "BGM Volume",
    graphics: "Graphics",
    particleQuality: "Particle Quality",
    low: "Low",
    medium: "Medium",
    high: "High",
    screenShake: "Screen Shake",
    showFPS: "Show FPS",
    accessibility: "Accessibility",
    colorBlindMode: "Colorblind Mode",
    showTrajectory: "Show Trajectory",
    gameOver: "Game Over!",
    clickToRestart: "Click to restart",
    finalScore: "Final Score: {score}",
    newHighScore: "🏆 New High Score! 🏆",
    newDailyChallenge: "New Daily Challenge!",
    checkTodaysChallenge: "Check out today's challenge",
    continue: "Continue",
    newGame: "New Game",
    statistics: "Statistics",
    achievements: "Achievements",
    leaderboard: "Leaderboard",
    adPlaceholder: "Ad (demo) completed successfully!",
    scoreToNextLevel: "Next level in {score} points",
    adblockTitle: "Adblock Detected",
    adblockMessage: "Please disable adblock and refresh to use items.",
    refresh: "Refresh",
    language: "Language",
    tutorialStartTitle: "Let's Start!",
    tutorialStartDescription:
      "Aim with your mouse and click to shoot a bubble.",
    tutorialMatchTitle: "Match Colors",
    tutorialMatchDescription:
      "Connect 3 or more bubbles of the same color to pop them.",
    tutorialItemsTitle: "Use Items",
    tutorialItemsDescription:
      "Click the items at the bottom to use special abilities.",
    tutorialDangerLineTitle: "Watch the Danger Line",
    tutorialDangerLineDescription:
      "If the bubbles cross the red dotted line, the game is over!",
    tutorialSkip: "Skip",
    tutorialNext: "Next",
    tutorialFinish: "Finish",
  },
  fr: {
    gameTitle: "Lanceur de Billes en Verre",
    score: "Score",
    highScore: "Meilleur Score",
    level: "Niveau",
    confirm: "Confirmer",
    close: "Fermer",
    reset: "Réinitialiser",
    save: "Sauvegarder",
    ad: "PUB",
    cancel: "Annuler",
    menu: "MENU",
    chances: "CHANCES",
    help: "Aide",
    helpLine1: "Visez avec la souris et cliquez pour tirer.",
    helpLine2:
      "Associez 3 bulles ou plus de la même couleur pour les faire éclater.",
    helpLine3: "Éliminez toutes les bulles pour passer au niveau suivant.",
    itemAim: "VISER",
    itemBomb: "BOMBE",
    itemAimActive: "VISÉE\nACTIVE",
    itemAimTitle: "Guide de visée",
    itemAimDescription:
      "Affiche la trajectoire exacte de la bulle pendant un court instant. Regarder une publicité pour obtenir cet objet ?",
    itemBombTitle: "Bulle Bombe",
    itemBombDescription:
      "Change la bulle actuelle en une bombe puissante. La bombe détruira les bulles voisines. Regarder une publicité pour obtenir cet objet ?",
    settings: "Paramètres",
    sound: "Son",
    masterVolume: "Volume Principal",
    sfxVolume: "Volume SFX",
    musicVolume: "Volume BGM",
    graphics: "Graphismes",
    particleQuality: "Qualité des Particules",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    screenShake: "Secousse d'Écran",
    showFPS: "Afficher FPS",
    accessibility: "Accessibilité",
    colorBlindMode: "Mode Daltonien",
    showTrajectory: "Afficher la Trajectoire",
    gameOver: "Partie Terminée !",
    clickToRestart: "Cliquez pour recommencer",
    finalScore: "Score Final : {score}",
    newHighScore: "🏆 Nouveau Meilleur Score ! 🏆",
    newDailyChallenge: "Nouveau Défi Quotidien !",
    checkTodaysChallenge: "Découvrez le défi d'aujourd'hui",
    continue: "Continuer",
    newGame: "Nouvelle Partie",
    statistics: "Statistiques",
    achievements: "Succès",
    leaderboard: "Classement",
    adPlaceholder: "Publicité (démo) terminée avec succès !",
    scoreToNextLevel: "Prochain niveau dans {score} points",
    adblockTitle: "Adblock Détecté",
    adblockMessage:
      "Veuillez désactiver adblock et actualiser pour utiliser les objets.",
    refresh: "Actualiser",
    language: "Langue",
    tutorialStartTitle: "Commençons !",
    tutorialStartDescription:
      "Visez avec votre souris et cliquez pour tirer une bulle.",
    tutorialMatchTitle: "Associez les couleurs",
    tutorialMatchDescription:
      "Connectez 3 bulles ou plus de la même couleur pour les faire éclater.",
    tutorialItemsTitle: "Utilisez les objets",
    tutorialItemsDescription:
      "Cliquez sur les objets en bas pour utiliser des capacités spéciales.",
    tutorialDangerLineTitle: "Attention à la ligne de danger",
    tutorialDangerLineDescription:
      "Si les bulles franchissent la ligne pointillée rouge, la partie est terminée !",
    tutorialSkip: "Passer",
    tutorialNext: "Suivant",
    tutorialFinish: "Terminer",
  },
  it: {
    gameTitle: "Lanceur de Billes en Verre",
    score: "Punteggio",
    highScore: "Punteggio Massimo",
    level: "Livello",
    confirm: "Conferma",
    close: "Chiudi",
    reset: "Ripristina",
    save: "Salva",
    ad: "PUB",
    cancel: "Annulla",
    menu: "MENU",
    chances: "POSSIBILITÀ",
    help: "Aiuto",
    helpLine1: "Mira con il mouse e clicca per sparare.",
    helpLine2: "Abbina 3 o più bolle dello stesso colore per scoppiarle.",
    helpLine3: "Elimina tutte le bolle per passare al livello successivo.",
    itemAim: "MIRA",
    itemBomb: "BOMBA",
    itemAimActive: "MIRA\nATTIVA",
    itemAimTitle: "Guida alla mira",
    itemAimDescription:
      "Mostra il percorso esatto della bolla per un breve periodo. Guardare un annuncio per ottenere questo oggetto?",
    itemBombTitle: "Bolla Bomba",
    itemBombDescription:
      "Trasforma la bolla attuale in una potente bomba. La bomba distruggerà le bolle vicine. Guardare un annuncio per ottenere questo oggetto?",
    settings: "Impostazioni",
    sound: "Suono",
    masterVolume: "Volume Principale",
    sfxVolume: "Volume SFX",
    musicVolume: "Volume BGM",
    graphics: "Grafica",
    particleQuality: "Qualità Particelle",
    low: "Bassa",
    medium: "Media",
    high: "Alta",
    screenShake: "Scuotimento Schermo",
    showFPS: "Mostra FPS",
    accessibility: "Accessibilità",
    colorBlindMode: "Modalità Daltonici",
    showTrajectory: "Mostra Traiettoria",
    gameOver: "Fine Partita!",
    clickToRestart: "Clicca per riavviare",
    finalScore: "Punteggio Finale: {score}",
    newHighScore: "🏆 Nuovo Punteggio Massimo! 🏆",
    newDailyChallenge: "Nuova Sfida Giornaliera!",
    checkTodaysChallenge: "Scopri la sfida di oggi",
    continue: "Continua",
    newGame: "Nuova Partita",
    statistics: "Statistiche",
    achievements: "Obiettivi",
    leaderboard: "Classifica",
    adPlaceholder: "Annuncio (demo) completato con successo!",
    scoreToNextLevel: "Prossimo livello tra {score} punti",
    adblockTitle: "Adblock Rilevato",
    adblockMessage: "Disabilita adblock e aggiorna per usare gli oggetti.",
    refresh: "Aggiorna",
    language: "Lingua",
    tutorialStartTitle: "Iniziamo!",
    tutorialStartDescription:
      "Mira con il mouse e clicca per sparare una bolla.",
    tutorialMatchTitle: "Abbina i colori",
    tutorialMatchDescription:
      "Collega 3 o più bolle dello stesso colore per scoppiarle.",
    tutorialItemsTitle: "Usa gli oggetti",
    tutorialItemsDescription:
      "Clicca sugli oggetti in basso per usare abilità speciali.",
    tutorialDangerLineTitle: "Attenzione alla linea di pericolo",
    tutorialDangerLineDescription:
      "Se le bolle superano la linea tratteggiata rossa, la partita è finita!",
    tutorialSkip: "Salta",
    tutorialNext: "Avanti",
    tutorialFinish: "Fine",
  },
  de: {
    gameTitle: "Glaskugel-Shooter",
    score: "Punktzahl",
    highScore: "Highscore",
    level: "Level",
    confirm: "Bestätigen",
    close: "Schließen",
    reset: "Zurücksetzen",
    save: "Speichern",
    ad: "WERBUNG",
    cancel: "Abbrechen",
    menu: "MENÜ",
    chances: "CHANCEN",
    help: "Hilfe",
    helpLine1: "Ziele mit der Maus und klicke, um zu schießen.",
    helpLine2:
      "Kombiniere 3 oder mehr gleichfarbige Blasen, um sie platzen zu lassen.",
    helpLine3: "Entferne alle Blasen, um zum nächsten Level zu gelangen.",
    itemAim: "ZIELEN",
    itemBomb: "BOMBE",
    itemAimActive: "ZIELEN\nAKTIV",
    itemAimTitle: "Zielhilfe",
    itemAimDescription:
      "Zeigt den genauen Weg der Blase für kurze Zeit. Werbung ansehen, um diesen Gegenstand zu erhalten?",
    itemBombTitle: "Bombenblase",
    itemBombDescription:
      "Verwandelt die aktuelle Blase in eine starke Bombe. Die Bombe zerstört nahegelegene Blasen. Werbung ansehen, um diesen Gegenstand zu erhalten?",
    settings: "Einstellungen",
    sound: "Ton",
    masterVolume: "Master-Lautstärke",
    sfxVolume: "SFX-Lautstärke",
    musicVolume: "BGM-Lautstärke",
    graphics: "Grafik",
    particleQuality: "Partikelqualität",
    low: "Niedrig",
    medium: "Mittel",
    high: "Hoch",
    screenShake: "Bildschirmwackeln",
    showFPS: "FPS anzeigen",
    accessibility: "Barrierefreiheit",
    colorBlindMode: "Farbenblind-Modus",
    showTrajectory: "Flugbahn anzeigen",
    gameOver: "Spiel Vorbei!",
    clickToRestart: "Klicken zum Neustarten",
    finalScore: "Endpunktzahl: {score}",
    newHighScore: "🏆 Neuer Highscore! 🏆",
    newDailyChallenge: "Neue Tägliche Herausforderung!",
    checkTodaysChallenge: "Schau dir die heutige Herausforderung an",
    continue: "Fortsetzen",
    newGame: "Neues Spiel",
    statistics: "Statistiken",
    achievements: "Erfolge",
    leaderboard: "Bestenliste",
    adPlaceholder: "Werbung (Demo) erfolgreich abgeschlossen!",
    scoreToNextLevel: "Nächstes Level in {score} Punkten",
    adblockTitle: "Adblock Entdeckt",
    adblockMessage:
      "Bitte deaktiviere Adblock und aktualisiere, um Gegenstände zu verwenden.",
    refresh: "Aktualisieren",
    language: "Sprache",
    tutorialStartTitle: "Fangen wir an!",
    tutorialStartDescription:
      "Ziele mit der Maus und klicke, um eine Blase zu schießen.",
    tutorialMatchTitle: "Farben kombinieren",
    tutorialMatchDescription:
      "Verbinde 3 oder mehr gleichfarbige Blasen, um sie platzen zu lassen.",
    tutorialItemsTitle: "Gegenstände benutzen",
    tutorialItemsDescription:
      "Klicke auf die Gegenstände unten, um Spezialfähigkeiten zu nutzen.",
    tutorialDangerLineTitle: "Achte auf die Gefahrenlinie",
    tutorialDangerLineDescription:
      "Wenn die Blasen die rot gestrichelte Linie überqueren, ist das Spiel vorbei!",
    tutorialSkip: "Überspringen",
    tutorialNext: "Weiter",
    tutorialFinish: "Fertig",
  },
  es: {
    gameTitle: "Disparador de Bolas de Cristal",
    score: "Puntuación",
    highScore: "Puntuación Más Alta",
    level: "Nivel",
    confirm: "Confirmar",
    close: "Cerrar",
    reset: "Reiniciar",
    save: "Guardar",
    ad: "ANUNCIO",
    cancel: "Cancelar",
    menu: "MENÚ",
    chances: "OPORTUNIDADES",
    help: "Ayuda",
    helpLine1: "Apunta con el ratón y haz clic para disparar.",
    helpLine2: "Combina 3 o más burbujas del mismo color para reventarlas.",
    helpLine3: "Elimina todas las burbujas para avanzar al siguiente nivel.",
    itemAim: "APUNTAR",
    itemBomb: "BOMBA",
    itemAimActive: "APUNTAR\nACTIVO",
    itemAimTitle: "Guía de Puntería",
    itemAimDescription:
      "Muestra la trayectoria exacta de la burbuja por un corto tiempo. ¿Ver un anuncio para obtener este objeto?",
    itemBombTitle: "Burbuja Bomba",
    itemBombDescription:
      "Cambia la burbuja actual por una bomba poderosa. La bomba destruirá las burbujas cercanas. ¿Ver un anuncio para obtener este objeto?",
    settings: "Ajustes",
    sound: "Sonido",
    masterVolume: "Volumen Principal",
    sfxVolume: "Volumen SFX",
    musicVolume: "Volumen BGM",
    graphics: "Gráficos",
    particleQuality: "Calidad de Partículas",
    low: "Baja",
    medium: "Media",
    high: "Alta",
    screenShake: "Sacudida de Pantalla",
    showFPS: "Mostrar FPS",
    accessibility: "Accesibilidad",
    colorBlindMode: "Modo Daltónico",
    showTrajectory: "Mostrar Trayectoria",
    gameOver: "¡Fin del Juego!",
    clickToRestart: "Haz clic para reiniciar",
    finalScore: "Puntuación Final: {score}",
    newHighScore: "🏆 ¡Nueva Puntuación Más Alta! 🏆",
    newDailyChallenge: "¡Nuevo Desafío Diario!",
    checkTodaysChallenge: "Echa un vistazo al desafío de hoy",
    continue: "Continuar",
    newGame: "Nuevo Juego",
    statistics: "Estadísticas",
    achievements: "Logros",
    leaderboard: "Clasificación",
    adPlaceholder: "¡Anuncio (demo) completado con éxito!",
    scoreToNextLevel: "Siguiente nivel en {score} puntos",
    adblockTitle: "Adblock Detectado",
    adblockMessage:
      "Por favor, deshabilita adblock y actualiza para usar los objetos.",
    refresh: "Actualizar",
    language: "Idioma",
    tutorialStartTitle: "¡Empecemos!",
    tutorialStartDescription:
      "Apunta con el ratón y haz clic para disparar una burbuja.",
    tutorialMatchTitle: "Combina colores",
    tutorialMatchDescription:
      "Conecta 3 o más burbujas del mismo color para reventarlas.",
    tutorialItemsTitle: "Usa objetos",
    tutorialItemsDescription:
      "Haz clic en los objetos de abajo para usar habilidades especiales.",
    tutorialDangerLineTitle: "Cuidado con la línea de peligro",
    tutorialDangerLineDescription:
      "Si las burbujas cruzan la línea de puntos roja, ¡el juego termina!",
    tutorialSkip: "Saltar",
    tutorialNext: "Siguiente",
    tutorialFinish: "Finalizar",
  },
  "zh-CN": {
    gameTitle: "珠子射手",
    score: "分数",
    highScore: "最高分",
    level: "等级",
    confirm: "确认",
    close: "关闭",
    reset: "重置",
    save: "保存",
    ad: "广告",
    cancel: "取消",
    menu: "菜单",
    chances: "机会",
    help: "帮助",
    helpLine1: "用鼠标瞄准并点击发射。",
    helpLine2: "匹配3个或更多相同颜色的泡泡来消除它们。",
    helpLine3: "清除所有泡泡以进入下一关。",
    itemAim: "瞄准",
    itemBomb: "炸弹",
    itemAimActive: "瞄准\n激活",
    itemAimTitle: "瞄准指南",
    itemAimDescription: "短时间内显示泡泡的精确路径。观看广告以获得此物品？",
    itemBombTitle: "炸弹泡泡",
    itemBombDescription:
      "将当前泡泡变成一个强大的炸弹。炸弹会摧毁附近的泡泡。观看广告以获得此物品？",
    settings: "设置",
    sound: "声音",
    masterVolume: "主音量",
    sfxVolume: "音效音量",
    musicVolume: "背景音乐音量",
    graphics: "图像",
    particleQuality: "粒子质量",
    low: "低",
    medium: "中",
    high: "高",
    screenShake: "屏幕震动",
    showFPS: "显示FPS",
    accessibility: "辅助功能",
    colorBlindMode: "色盲模式",
    showTrajectory: "显示轨迹",
    gameOver: "游戏结束！",
    clickToRestart: "点击重新开始",
    finalScore: "最终得分: {score}",
    newHighScore: "🏆 新的最高分！ 🏆",
    newDailyChallenge: "新的每日挑战！",
    checkTodaysChallenge: "查看今天的挑战",
    continue: "继续",
    newGame: "新游戏",
    statistics: "统计",
    achievements: "成就",
    leaderboard: "排行榜",
    adPlaceholder: "广告（演示）成功完成！",
    scoreToNextLevel: "距离下一级还差 {score} 分",
    adblockTitle: "检测到广告拦截器",
    adblockMessage: "请禁用广告拦截器并刷新以使用物品。",
    refresh: "刷新",
    language: "语言",
    tutorialStartTitle: "让我们开始吧！",
    tutorialStartDescription: "用鼠标瞄准并点击发射泡泡。",
    tutorialMatchTitle: "匹配颜色",
    tutorialMatchDescription: "连接3个或更多相同颜色的泡泡以消除它们。",
    tutorialItemsTitle: "使用道具",
    tutorialItemsDescription: "点击底部的道具以使用特殊能力。",
    tutorialDangerLineTitle: "注意危险线",
    tutorialDangerLineDescription: "如果泡泡越过红色虚线，游戏就结束了！",
    tutorialSkip: "跳过",
    tutorialNext: "下一个",
    tutorialFinish: "完成",
  },
  ja: {
    gameTitle: "ビーズシューター",
    score: "スコア",
    highScore: "ハイスコア",
    level: "レベル",
    confirm: "確認",
    close: "閉じる",
    reset: "リセット",
    save: "保存",
    ad: "広告",
    cancel: "キャンセル",
    menu: "メニュー",
    chances: "チャンス",
    help: "ヘルプ",
    helpLine1: "マウスで狙いを定めてクリックして撃ちます。",
    helpLine2: "同じ色のバブルを3つ以上つなげて消します。",
    helpLine3: "すべてのバブルを消して次のレベルに進みます。",
    itemAim: "照準",
    itemBomb: "爆弾",
    itemAimActive: "照準\n有効",
    itemAimTitle: "照準ガイド",
    itemAimDescription:
      "短時間、バブルの正確な軌道を表示します。広告を見てこのアイテムを入手しますか？",
    itemBombTitle: "爆弾バブル",
    itemBombDescription:
      "現在のバブルを強力な爆弾に変えます。爆弾は近くのバブルを破壊します。広告を見てこのアイテムを入手しますか？",
    settings: "設定",
    sound: "サウンド",
    masterVolume: "マスター音量",
    sfxVolume: "SFX音量",
    musicVolume: "BGM音量",
    graphics: "グラフィック",
    particleQuality: "パーティクルの品質",
    low: "低",
    medium: "中",
    high: "高",
    screenShake: "画面の揺れ",
    showFPS: "FPSを表示",
    accessibility: "アクセシビリティ",
    colorBlindMode: "色覚異常モード",
    showTrajectory: "軌道を表示",
    gameOver: "ゲームオーバー！",
    clickToRestart: "クリックして再起動",
    finalScore: "最終スコア: {score}",
    newHighScore: "🏆 新しいハイスコア！ 🏆",
    newDailyChallenge: "新しいデイリーチャレンジ！",
    checkTodaysChallenge: "今日のチャレンジをチェック",
    continue: "続ける",
    newGame: "新しいゲーム",
    statistics: "統計",
    achievements: "実績",
    leaderboard: "リーダーボード",
    adPlaceholder: "広告（デモ）が正常に完了しました！",
    scoreToNextLevel: "次のレベルまであと{score}ポイント",
    adblockTitle: "広告ブロッカーが検出されました",
    adblockMessage:
      "アイテムを使用するには、広告ブロッカーを無効にして更新してください。",
    refresh: "更新",
    language: "言語",
    tutorialStartTitle: "始めましょう！",
    tutorialStartDescription:
      "マウスで狙いを定めてクリックし、バブルを発射します。",
    tutorialMatchTitle: "色を合わせる",
    tutorialMatchDescription: "同じ色のバブルを3つ以上つなげて消します。",
    tutorialItemsTitle: "アイテムを使用する",
    tutorialItemsDescription:
      "下部のアイテムをクリックして特殊能力を使用します。",
    tutorialDangerLineTitle: "危険なラインに注意",
    tutorialDangerLineDescription:
      "バブルが赤い点線を越えるとゲームオーバーです！",
    tutorialSkip: "スキップ",
    tutorialNext: "次へ",
    tutorialFinish: "終了",
  },
  ko: {
    gameTitle: "비즈 슈터",
    score: "점수",
    highScore: "최고 점수",
    level: "레벨",
    confirm: "확인",
    close: "닫기",
    reset: "초기화",
    save: "저장",
    ad: "광고",
    cancel: "취소",
    menu: "메뉴",
    chances: "기회",
    help: "도움말",
    helpLine1: "마우스로 조준하고 클릭하여 발사하세요.",
    helpLine2: "같은 색의 버블을 3개 이상 맞추면 터집니다.",
    helpLine3: "모든 버블을 제거하면 다음 레벨로 넘어갑니다.",
    itemAim: "조준",
    itemBomb: "폭탄",
    itemAimActive: "조준\n활성",
    itemAimTitle: "조준 가이드",
    itemAimDescription:
      "짧은 시간 동안 버블의 정확한 경로를 보여줍니다. 광고를 보고 이 아이템을 얻으시겠습니까?",
    itemBombTitle: "폭탄 버블",
    itemBombDescription:
      "현재 버블을 강력한 폭탄으로 바꿉니다. 폭탄은 주변 버블을 파괴합니다. 광고를 보고 이 아이템을 얻으시겠습니까?",
    settings: "설정",
    sound: "사운드",
    masterVolume: "마스터 볼륨",
    sfxVolume: "효과음 볼륨",
    musicVolume: "배경음악 볼륨",
    graphics: "그래픽",
    particleQuality: "파티클 품질",
    low: "낮음",
    medium: "중간",
    high: "높음",
    screenShake: "화면 흔들림",
    showFPS: "FPS 표시",
    accessibility: "접근성",
    colorBlindMode: "색맹 모드",
    showTrajectory: "궤적 표시",
    gameOver: "게임 오버!",
    clickToRestart: "클릭하여 다시 시작",
    finalScore: "최종 점수: {score}",
    newHighScore: "🏆 새로운 최고 점수! 🏆",
    newDailyChallenge: "새로운 일일 도전!",
    checkTodaysChallenge: "오늘의 도전 확인하기",
    continue: "계속하기",
    newGame: "새 게임",
    statistics: "통계",
    achievements: "업적",
    leaderboard: "리더보드",
    adPlaceholder: "광고(데모)가 성공적으로 완료되었습니다!",
    scoreToNextLevel: "{score}점 후 다음 레벨",
    adblockTitle: "애드블록 감지됨",
    adblockMessage:
      "아이템을 사용하려면 애드블록을 비활성화하고 새로고침하세요.",
    refresh: "새로고침",
    language: "언어",
    tutorialStartTitle: "시작합시다!",
    tutorialStartDescription: "마우스로 조준하고 클릭하여 버블을 쏘세요.",
    tutorialMatchTitle: "색깔 맞추기",
    tutorialMatchDescription: "같은 색깔의 버블을 3개 이상 연결하면 터집니다.",
    tutorialItemsTitle: "아이템 사용하기",
    tutorialItemsDescription: "아래 아이템을 클릭하여 특수 능력을 사용하세요.",
    tutorialDangerLineTitle: "데인저 라인을 조심하세요",
    tutorialDangerLineDescription:
      "버블이 빨간 점선을 넘으면 게임이 종료됩니다!",
    tutorialSkip: "건너뛰기",
    tutorialNext: "다음",
    tutorialFinish: "완료",
  },
};

let currentLanguage = "en";
const languageChangeListeners = [];

export function setLanguage(lang) {
  if (translations[lang]) {
    currentLanguage = lang;
    languageChangeListeners.forEach((listener) => listener(lang));
  } else {
    console.warn(`Language '${lang}' not found. Falling back to English.`);
    currentLanguage = "en";
  }
}

export function getLocalizedString(key, replacements = {}) {
  const langTranslations = translations[currentLanguage] || translations.en;
  let text = langTranslations[key] || translations.en[key] || key;
  for (const placeholder in replacements) {
    text = text.replace(`{${placeholder}}`, replacements[placeholder]);
  }
  return text;
}

export function onLanguageChange(listener) {
  languageChangeListeners.push(listener);
}
